### ISSUE TITLE
Lists in RequirementEntities are causing the build to fail

### ISSUE THREAD

**Issue by bingemi** [watermelonfarmers/watermelon#1]
The application will not be able to start as Hibernate / JPA is not able to model lists without a key reference to another entity, or perhaps this solution...

https://stackoverflow.com/questions/5867130/hibernate-liststring

**Comment by TargaryenQi** [comment]
Great, I will try this solution!

**Comment by TargaryenQi** [comment]
I have deleted these lists for now and after I figuring out how to implement them, I will then add them back.

**Comment by TargaryenQi** [comment]
I have use @OneToMany and @ManyToOne in Comment List and it works well for now. Maybe later, some other problems will come out.
